### ISSUE TITLE
credit_names is invalid

### ISSUE THREAD

**Issue by marius851000** [PMDCollab/SpriteCollab#3]
Hello. After someone told me I miscredited her, I figured the credit_names has way too much entry, most of them are invalid python object (CreditNode). They also appear in the online interface, making this page take a long time to load.

![image](https://user-images.githubusercontent.com/22586596/136274446-8acdcc43-0bb1-4776-8264-847e141503b7.png)

**Comment by marius851000** [comment]
(ps: the last line is a valid id)

**Comment by audinowho** [comment]
Fixed in https://github.com/PMDCollab/SpriteCollab/commit/4a1850e98ae7dc897b478f1c9de71336216a1417
