### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GadgeurX** [PMDCollab/SpriteCollab#5]
Hello ! You database is incredible, welldone. 

I have a question about how to get the attacks sprites ? I cannot find any resources on the web for this problem.

Thanks for a response.

**Comment by keldaan-ag** [comment]
SpriteCollab/sprite/__index__/Attack-anim.png

**Comment by GadgeurX** [comment]
Hi ! Sorry to reopen this thread but there are no attack sprites. These are the attacking character sprites. Do you know where I can find the attack sprites?

**Comment by keldaan-ag** [comment]
https://www.spriters-resource.com/ds_dsi/pokemonmysterydungeonexplorersofsky/sheet/85692/

**Comment by GadgeurX** [comment]
Yes !! Thanks you very much !!
